### PR TITLE
handling of multiple groups with same name

### PR DESCRIPTION
**Pull request by jfburkhart**
@leifdenby added the ability to handle namelist files with multiple groups with common group name. Also includes double quote string handling per PR#1 (hope that doesn't make the merge difficult)

### CODE REVIEW

**Comment by leifdenby** [comment]
Cheers @jfburkhart. Did you write a test for this yourself while developing this? If you did maybe you could add `test_` function with that code? It would be good to have a test for this. I didn't even realise that namelist files could contain multiple groups with the same name.

**Comment by jfburkhart** [comment]
Hi, how do you run your tests actually? I just cloned your repo directly, and get a lot of errors if I just run:

```
python namelist.py
```

Which it seems like what to do given how you have unittest setup.

I've tried to write a `test_commongroup_names` for my case, but it also fails...

```
     def test_commongroup_names(self):
         input_str = """&RELEASES_CTR
 NSPEC=        1,
 SPECNUM_REL= 100,   
 /
 &RELEASE
  IDATE1=  20100101,
  ITIME1=  000000,
  IDATE2=  20100201,
  ITIME2=  000000,
 /
 &RELEASE
  IDATE1=  20100101,
  ITIME1=  000000,
  IDATE2=  20100201,
  ITIME2=  000000,
 /"""
    namelist = Namelist(input_str)
    self.assertEqual(namelist.dump(array_inline=False), input_str)
```

**Comment by jfburkhart** [comment]
Although, I just realized! Doh... it will of course fail, as I append cnts to the names! Have to think a bit more on this.

**Comment by jfburkhart** [comment]
@leifdenby tests are added now using re module. Not sure it's robust, but it is a test! ;)

**Comment by jfburkhart** [comment]
@leifdenby, I had to double check out the multiple group names, seems it is okay:
[ google book result F90](https://books.google.no/books?id=DsLgBwAAQBAJ&lpg=SA9-PA43&ots=op4RaXUglb&dq=namelist%20group%20same%20name&pg=SA9-PA44#v=onepage&q=namelist%20group%20same%20name&f=false)

But, I suppose if this is a robust implementation, then the approach I've introduced isn't optimal, as it won't recreate the identical structure with `.dump`. Since Dicts require a unique key, your approach won't provide a mechanism that is immediately obvious. The fix in place works for my case, but maybe we should create an issue to fix it properly if you accept this PR.

**Comment by leifdenby** [comment]
Thanks for this @jfburkhart ! Sorry it took so long for me to merge this

**Pull request merged**
